default_language_version:
  node: 16.14.2
repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.0
  hooks:
  - id: pyupgrade
    args: [--py3-plus]
- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
  - id: docformatter
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: [--filter-files]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/executablebooks/mdformat.git
  rev: 0.7.14
  hooks:
  - id: mdformat
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=800]
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-yaml
  - id: fix-byte-order-marker
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: trailing-whitespace
